### ISSUE TITLE
Expected two fields per line in training data, got 1 for line 'De Art O'!

### ISSUE THREAD

**Issue by asmundur** [ixa-ehu/ixa-pipe-ml#7]
Just trying to get the training to work on the a Dutch CoNLL 2002 file, I get this error, what am I doing wrong? 

`	Computing event counts...  java.io.IOException: Expected two fields per line in training data, got 1 for line 'De Art O'!
Incorporating indexed data for training...  
Exception in thread "main" java.lang.NullPointerException
	at opennlp.tools.ml.perceptron.PerceptronTrainer.trainModel(PerceptronTrainer.java:199)
	at opennlp.tools.ml.perceptron.PerceptronTrainer.doTrain(PerceptronTrainer.java:131)
	at opennlp.tools.ml.perceptron.PerceptronTrainer.doTrain(PerceptronTrainer.java:38)
	at opennlp.tools.ml.AbstractEventTrainer.train(AbstractEventTrainer.java:93)
	at eus.ixa.ixa.pipe.ml.sequence.SequenceLabelerME.train(SequenceLabelerME.java:272)
	at eus.ixa.ixa.pipe.ml.SequenceLabelerTrainer.train(SequenceLabelerTrainer.java:193)
	at eus.ixa.ixa.pipe.ml.CLI.seqTrain(CLI.java:244)
	at eus.ixa.ixa.pipe.ml.CLI.parseCLI(CLI.java:187)
	at eus.ixa.ixa.pipe.ml.CLI.main(CLI.java:170)
`

**Comment by ragerri** [comment]
You need to format the data. The system is expecting word tabulated NER
class newline for each line. And empty lines to delimit the sentences.

See the attached development and test sets formatted in the format that ixa
pipes requires.

R

**Comment by asmundur** [comment]
Thanks for a real quick response

**Comment by asmundur** [comment]
Excuse me, where are the attached development and test sets? I'm not finding them.

**Comment by ragerri** [comment]
Ah, attachments do not go into the github directly.

You can get them here:

http://ixa2.si.ehu.es/ragerri/nl-conll02.tar.gz

Cheers,

R
